# Generated by Django 4.1.3 on 2023-09-07 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_link_mock_delete_tip_alter_student_cource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mock',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mock',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (1, 'Disactive')], default=1),
        ),
    ]
